### ISSUE TITLE
自动获取token状态:失败,更多信息:环境：【test】数据格式出错，请检查

### ISSUE THREAD

**Issue by xiaojian520** [shouldnotappearcalm/yapi-plugin-interface-oauth2#47]
![1632829111(1)](https://user-images.githubusercontent.com/6177311/135080334-7c8e0d5d-cb52-4b5e-85f0-5246569b2704.jpg)

**Comment by shouldnotappearcalm** [comment]
项目是否存在访客用户

**Comment by xiaojian520** [comment]
> 项目是否存在访客用户

666 把访客改了就好了 谢谢
